### ISSUE TITLE
Lab 1: Part 6: Step 6 : Screen blank while step by step debugging

### ISSUE THREAD

**Issue by vik17ag** [aporter/coursera-android#43]
Hi,

While using debugger with a breakpoint       at int val = findAnswer();

My phone screen is black, and I cannot see words "The answer to life,universe and everything is"  ,

Only when i resume program, the screen shows all the words "The answer to life,universe and everything is 42"

Pls help..

**Comment by filipebezerra** [comment]
Can you provide a printscreen?

**Comment by campbe13** [comment]
The problem is where you put you breakpoint, the display is done after it.  Put in breakpoings before and after and you may see what you want.  Debugging apps involves a lot of back and forth to the debugger & the running code.  Rule of thumb: a lot of breakpoints, figure out where you are, streamline breakpoints.
